### ISSUE TITLE
New version errors and connection problems

### ISSUE THREAD

**Issue by behabecker** [iadgov/goSecure#1]
I just downloaded the latest version of the webGUI client via https://iadgov.github.io/goSecure/files/install_scripts/gosecure_client_install.py
The file contained two indent issues that need to be fixed, but that's not the biggest issue. After installing this version and launching, if I go to https://setup.gosecure/ and enter my user/pass combination, I am redirected to a 500 Internal Server Error page. In the past, this hasn't been an issue, as I could navigate to any other page and have it load appropriately. Unfortunately now I can no longer do this. I ssh'd into the pi and tried to ping out to any IP addresses but was unable to reach anything external. Thanks.

**Comment by iadgovuser7** [comment]
The indent issues have been fixed and you should no longer get the 500 Internal Server Error once you update to the latest client GUI version. A "Update Client" option has been added to the menu to make the update process easier.
